"""create user tables

Revision ID: e463f016a6c2
Revises:
Create Date: 2025-08-22 22:28:02.764208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e463f016a6c2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "user_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "access_role", sa.Enum("USER", "ADMIN", name="accessrole"), nullable=False
        ),
        sa.Column(
            "subscription",
            sa.Enum("FREE", "PRO", "PREMIUM", name="subscription"),
            nullable=False,
        ),
        sa.Column(
            "language_level",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="languagelevel"),
            nullable=False,
        ),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_info")
    op.drop_table("users")
    op.execute('DROP TYPE IF EXISTS accessrole')
    op.execute('DROP TYPE IF EXISTS languagelevel')
    op.execute('DROP TYPE IF EXISTS subscription')
    # ### end Alembic commands ###
